services:
  coolify-db:
    image: postgres:15-alpine
    container_name: coolify-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: coolify
      POSTGRES_USER: coolify
      POSTGRES_PASSWORD: coolify
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coolify"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  coolify-redis:
    image: redis:7-alpine
    container_name: coolify-redis
    restart: unless-stopped
    volumes:
      - ./redis-data:/data

  coolify:
    image: coollabsio/coolify:latest
    container_name: coolify
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "80:80"
      - "443:443"
    environment:
      APP_ENV: production
      APP_URL: http://localhost

      DB_CONNECTION: pgsql
      DB_HOST: coolify-db
      DB_PORT: 5432
      DB_DATABASE: coolify
      DB_USERNAME: coolify
      DB_PASSWORD: coolify
      APP_KEY: base64:Kz9Tn7lNfE+G0e6Z8kXHg9tS6IjE1qPwr2tXG6C/4lQ=


      REDIS_HOST: coolify-redis
    depends_on:
      coolify-db:
        condition: service_healthy
      coolify-redis:
        condition: service_started
    volumes:
      - ./coolify-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
